---
- hosts: mytarget
  vars:
    login_user: li


  tasks:
  - name: show host
    debug: msg="hostname is {{ host_name }}"

  - name: set hostname
    hostname: name={{ host_name }} 
  - name: sync hosts file
    template: src=templates/hosts.j2 dest=/etc/hosts  

  - name: install packages
    apt: pkg={{ item }} state=present 
    with_items:
    - tmux
    - tcpdump
    - vim
    - clusterssh
    - zsh
    - git
    - curl
    - sudo


  - name: configure vim
    copy: src=files/vimrc dest=/home/{{login_user}}/.vimrc

  - name: check oh my zsh
    stat: path=/home/{{login_user}}/.oh-my-zsh
    register: zsh
  
  - name: task of installing oh my zsh
    include: tasks/install_zsh.yml
    when: ! zsh.stat.exists

  
    
