---
- hosts: mytarget
  vars:
    login_user: li


  tasks:
  - name: set hostname
    hostname: name={{ host_name }} 

  - name: sync hosts file
    template: src=templates/hosts.j2 dest=/etc/hosts  

  - name: install packages
    apt: pkg={{ item }} state=present 
    with_items:
    - tmux
    - byobu
    - tcpdump
    - vim
    - clusterssh
    - zsh
    - git
    - curl
    - sudo
    - tree
    - mlocate
    - rsync

  - name: configure vim
    copy: src=files/vimrc dest=/home/{{login_user}}/.vimrc


  - name: configure puppet
    copy: src=files/puppet.conf dest=/etc/puppet/

  - name: check oh my zsh
    stat: path=/home/{{login_user}}/.oh-my-zsh
    register: zsh
  
  - name: task of installing oh my zsh
    include: tasks/install_zsh.yml
    when: ! zsh.stat.exists

  
    
